### PR TITLE
remove unused bin/ CLI interface

### PR DESCRIPTION
**Pull request by FredKSchott**
Is the CLI interface created in the`bin/` directory used anywhere? It seems like it's existed since the early days of this repo, but it doesn't look like its ever been registered as a `bin` command in package.json.

/cc @rictic @azakus Safe to remove?

### CODE REVIEW

**Comment by rictic** [comment]
I don't have enough context to say on this one either way. Leaving to @azakus to review.

**Comment by azakus** [comment]
Oh, there is at least one user for it. Can you just add it as a binary in the package.json instead?

**Comment by FredKSchott** [comment]
After in person discussion, we're going to leave the file and add a comment in bin/css-slam about its current use.

**Comment by FredKSchott** [comment]
@azakus ptal

**Pull request merged**
